"""IMAGINA V19 — Imagery Task Battery.

Defines a standardized local-first mental imagery task battery
with 30+ tasks across 10 categories.
"""

SAFETY = {
    "analysis_mode": "personal_exploratory_training",
    "not_clinical": True, "not_diagnostic": True,
    "not_mind_reading": True, "not_bci_claim": True,
    "production_valid": False,
    "scientific_boundary": ("Personal exploratory mental imagery training only. "
                             "Not diagnosis, therapy, clinical treatment, "
                             "mind-reading, dream decoding, or validated BCI."),
}

CATEGORIES = [
    "basic_vividness", "color_control", "spatial_stability",
    "detail_generation", "perspective_control", "motion_imagery",
    "emotional_tone_imagery", "scene_construction", "multisensory_imagery",
    "meta_control",
]

TASKS = [
    # ─── BASIC VIVIDNESS ───
    {"task_id": "red_circle_vividness", "title": "Red Circle Vividness",
     "category": "basic_vividness", "difficulty": 1,
     "target_dimensions": ["vividness", "color_control"],
     "prompt": "Visualize a vibrant red circle, smooth edges, centered in your visual field.",
     "instructions": ["Close your eyes.", "Build a clear mental image of the red circle.",
                      "Hold it as firmly as possible.", "Rate its vividness when ready."],
     "duration_seconds": 60,
     "dimension_weights": {"vividness": 0.6, "color_control": 0.4},
     "scoring_notes": "Higher vividness = clearer, more photographic mental image."},
    {"task_id": "blue_cube_vividness", "title": "Blue Cube Vividness",
     "category": "basic_vividness", "difficulty": 2,
     "target_dimensions": ["vividness", "spatial_control"],
     "prompt": "Visualize a solid dark blue cube with crisp edges, resting on a surface.",
     "instructions": ["Close your eyes.", "Build the 3D blue cube.", "Note its edges, faces, and depth.",
                      "Rate vividness and spatial clarity."],
     "duration_seconds": 75,
     "dimension_weights": {"vividness": 0.5, "spatial_control": 0.5}},
    {"task_id": "candle_flame_vividness", "title": "Candle Flame Vividness",
     "category": "basic_vividness", "difficulty": 2,
     "target_dimensions": ["vividness", "motion", "color_control"],
     "prompt": "Visualize a candle flame — flickering, orange-gold, with a blue base.",
     "instructions": ["Close your eyes.", "Build the candle flame image.",
                      "Observe its motion and color gradients.", "Rate vividness, color, and motion clarity."],
     "duration_seconds": 75,
     "dimension_weights": {"vividness": 0.4, "motion": 0.3, "color_control": 0.3}},
    # ─── COLOR CONTROL ───
    {"task_id": "color_shift_red_to_blue", "title": "Color Shift Red to Blue",
     "category": "color_control", "difficulty": 2,
     "target_dimensions": ["color_control", "meta_control"],
     "prompt": "Visualize a circle. Shift its color from red through purple to blue, holding each intermediate shade.",
     "instructions": ["Start with a red circle.", "Slowly transition to blue.",
                      "Hold 3 intermediate shades.", "Rate your control over the color shifts."],
     "duration_seconds": 90,
     "dimension_weights": {"color_control": 0.7, "meta_control": 0.3}},
    {"task_id": "saturation_control", "title": "Saturation Control",
     "category": "color_control", "difficulty": 3,
     "target_dimensions": ["color_control", "vividness"],
     "prompt": "Visualize a green sphere. Increase its saturation to maximum, then drain it to pale gray, and restore.",
     "instructions": ["Build the green sphere at medium saturation.",
                      "Push saturation to maximum vivid green.", "Drain color to nearly gray.",
                      "Restore original saturation.", "Rate your saturation control."],
     "duration_seconds": 90, "dimension_weights": {"color_control": 0.8, "vividness": 0.2}},
    {"task_id": "brightness_control", "title": "Brightness Control",
     "category": "color_control", "difficulty": 2,
     "target_dimensions": ["color_control", "vividness"],
     "prompt": "Visualize a yellow star. Make it brighter and brighter, then dim it gradually.",
     "instructions": ["Build the yellow star at normal brightness.", "Increase to high brightness.",
                      "Dim to near-darkness.", "Return to normal.", "Rate brightness control."],
     "duration_seconds": 75, "dimension_weights": {"color_control": 0.7, "vividness": 0.3}},
    # ─── SPATIAL STABILITY ───
    {"task_id": "static_cube_stability", "title": "Static Cube Stability",
     "category": "spatial_stability", "difficulty": 1,
     "target_dimensions": ["spatial_control", "vividness", "stability"],
     "prompt": "Visualize a stationary cube. Keep it completely still in your mind's eye.",
     "instructions": ["Visualize the cube.", "If it drifts, gently bring it back.",
                      "Hold position for the full duration.", "Rate stability."],
     "duration_seconds": 60, "dimension_weights": {"spatial_control": 0.5, "vividness": 0.2, "stability": 0.3}},
    {"task_id": "rotating_cube_stability", "title": "Rotating Cube Stability",
     "category": "spatial_stability", "difficulty": 3,
     "target_dimensions": ["spatial_control", "motion", "stability"],
     "prompt": "Visualize a cube rotating slowly clockwise. Maintain smooth, even rotation.",
     "instructions": ["Build the cube.", "Start slow clockwise rotation.",
                      "Keep the rotation steady and smooth.", "If it wobbles, steady it.", "Rate spatial and motion stability."],
     "duration_seconds": 90, "dimension_weights": {"spatial_control": 0.4, "motion": 0.3, "stability": 0.3}},
    {"task_id": "room_layout_stability", "title": "Room Layout Stability",
     "category": "spatial_stability", "difficulty": 3,
     "target_dimensions": ["spatial_control", "detail", "stability"],
     "prompt": "Visualize a simple room layout: a table, two chairs, a lamp. Keep the spatial relationship stable.",
     "instructions": ["Build the room layout.", "Note positions of objects relative to each other.",
                      "Hold the layout stable.", "Pan your view without losing object positions.", "Rate spatial stability."],
     "duration_seconds": 90, "dimension_weights": {"spatial_control": 0.5, "detail": 0.2, "stability": 0.3}},
    # ─── DETAIL GENERATION ───
    {"task_id": "apple_detail_generation", "title": "Apple Detail Generation",
     "category": "detail_generation", "difficulty": 2,
     "target_dimensions": ["detail", "vividness", "color_control"],
     "prompt": "Visualize a red apple. Add details: stem, leaf, subtle color variations, small spots on the skin.",
     "instructions": ["Start with a basic apple shape.", "Add the stem and a green leaf.",
                      "Add color variations and texture.", "Zoom in on a small detail.", "Rate your detail level."],
     "duration_seconds": 90, "dimension_weights": {"detail": 0.5, "vividness": 0.3, "color_control": 0.2}},
    {"task_id": "face_detail_generation", "title": "Face Detail Generation",
     "category": "detail_generation", "difficulty": 4,
     "target_dimensions": ["detail", "vividness", "spatial_control"],
     "prompt": "Visualize a familiar face. Add specific details: eye color, eyebrow shape, skin texture.",
     "instructions": ["Start with the face outline.", "Add eyes with specific color.",
                      "Add eyebrows, nose, mouth.", "Add skin texture and hair.", "Rate detail level.",
                      "Safety: if the face becomes distorted or uncomfortable, stop."],
     "duration_seconds": 120, "dimension_weights": {"detail": 0.6, "vividness": 0.2, "spatial_control": 0.2},
     "safety_note": "If the face becomes distorted, unclear, or uncomfortable, stop the exercise."},
    {"task_id": "forest_scene_detail", "title": "Forest Scene Detail",
     "category": "detail_generation", "difficulty": 4,
     "target_dimensions": ["detail", "spatial_control", "vividness"],
     "prompt": "Visualize a forest clearing. Add trees, undergrowth, light through leaves, texture of bark.",
     "instructions": ["Build the clearing.", "Add 3-5 trees with bark texture.",
                      "Add light filtering through leaves.", "Add undergrowth details.", "Rate detail richness."],
     "duration_seconds": 120, "dimension_weights": {"detail": 0.5, "spatial_control": 0.3, "vividness": 0.2}},
    # ─── PERSPECTIVE CONTROL ───
    {"task_id": "first_person_room_view", "title": "First-Person Room View",
     "category": "perspective_control", "difficulty": 2,
     "target_dimensions": ["spatial_control", "vividness"],
     "prompt": "Visualize a room from your own first-person perspective, as if you are standing inside it.",
     "instructions": ["Choose a familiar room.", "Build the view from your eye level.",
                      "Look around without moving.", "Rate how natural the perspective feels."],
     "duration_seconds": 75, "dimension_weights": {"spatial_control": 0.7, "vividness": 0.3}},
    {"task_id": "third_person_object_view", "title": "Third-Person Object View",
     "category": "perspective_control", "difficulty": 3,
     "target_dimensions": ["spatial_control", "meta_control"],
     "prompt": "Visualize a chair. Switch between seeing it from above, from the side, and from below.",
     "instructions": ["Build the chair.", "View it from above.", "Switch to side view.",
                      "Switch to below view.", "Return to neutral.", "Rate perspective control."],
     "duration_seconds": 90, "dimension_weights": {"spatial_control": 0.5, "meta_control": 0.5}},
    {"task_id": "perspective_shift_task", "title": "Perspective Shift",
     "category": "perspective_control", "difficulty": 4,
     "target_dimensions": ["spatial_control", "meta_control", "vividness"],
     "prompt": "Visualize an apple on a table. Shift from your eyes looking down at it to viewing from across the room.",
     "instructions": ["Build first-person view: looking down at apple.",
                      "Shift to across-room perspective.", "Hold the new perspective.",
                      "Shift back smoothly.", "Rate perspective shift control."],
     "duration_seconds": 90, "dimension_weights": {"spatial_control": 0.4, "meta_control": 0.4, "vividness": 0.2}},
    # ─── MOTION IMAGERY ───
    {"task_id": "rotating_object", "title": "Rotating Object",
     "category": "motion_imagery", "difficulty": 2,
     "target_dimensions": ["motion", "spatial_control"],
     "prompt": "Visualize a teacup rotating slowly. Keep the motion smooth and continuous.",
     "instructions": ["Build the teacup.", "Start slow rotation.", "Keep motion smooth.",
                      "If it jumps, re-stabilize.", "Rate motion quality."],
     "duration_seconds": 75, "dimension_weights": {"motion": 0.7, "spatial_control": 0.3}},
    {"task_id": "falling_leaf", "title": "Falling Leaf",
     "category": "motion_imagery", "difficulty": 3,
     "target_dimensions": ["motion", "vividness", "spatial_control"],
     "prompt": "Visualize an autumn leaf falling from a tree, drifting side to side as it descends.",
     "instructions": ["Build the tree and leaf.", "Let the leaf detach and fall.",
                      "Track its side-to-side drifting motion.", "Follow it to the ground.", "Rate motion quality."],
     "duration_seconds": 90, "dimension_weights": {"motion": 0.5, "vividness": 0.3, "spatial_control": 0.2}},
    {"task_id": "walking_path_simulation", "title": "Walking Path Simulation",
     "category": "motion_imagery", "difficulty": 4,
     "target_dimensions": ["motion", "spatial_control", "detail"],
     "prompt": "Visualize walking down a garden path. Simulate the forward motion and approaching objects.",
     "instructions": ["Build the path.", "Start walking forward.", "Observe objects approaching.",
                      "Maintain smooth forward motion.", "Rate motion and spatial quality."],
     "duration_seconds": 90, "dimension_weights": {"motion": 0.5, "spatial_control": 0.3, "detail": 0.2}},
    # ─── EMOTIONAL TONE IMAGERY ───
    {"task_id": "calm_scene_generation", "title": "Calm Scene Generation",
     "category": "emotional_tone_imagery", "difficulty": 2,
     "target_dimensions": ["emotion", "vividness"],
     "prompt": "Visualize a calm, peaceful scene of your choice. Let it feel soothing and quiet.",
     "instructions": ["Choose a calm scene.", "Build it clearly.", "Notice the emotional tone.",
                      "Let it feel peaceful and still.", "Rate the emotional tone and vividness.",
                      "Safety: if the scene becomes unpleasant, stop and open your eyes."],
     "duration_seconds": 75, "dimension_weights": {"emotion": 0.7, "vividness": 0.3},
     "safety_note": "If the scene becomes emotionally unpleasant, stop and open your eyes."},
    {"task_id": "joyful_memory_scene", "title": "Joyful Memory Scene",
     "category": "emotional_tone_imagery", "difficulty": 3,
     "target_dimensions": ["emotion", "detail", "vividness"],
     "prompt": "Recall a joyful memory scene. Reconstruct it with emotional warmth and visual detail.",
     "instructions": ["Choose a joyful memory.", "Reconstruct the scene visually.",
                      "Notice and hold the positive emotional tone.", "Add details as they come.",
                      "Rate emotional quality and detail.",
                      "Safety: if the memory becomes painful, choose a different scene."],
     "duration_seconds": 90, "dimension_weights": {"emotion": 0.5, "detail": 0.3, "vividness": 0.2},
     "safety_note": "If the memory becomes emotionally painful or uncomfortable, stop and choose a different scene."},
    {"task_id": "neutral_object_scene", "title": "Neutral Object Scene",
     "category": "emotional_tone_imagery", "difficulty": 1,
     "target_dimensions": ["emotion", "vividness"],
     "prompt": "Visualize a neutral object like a plain white cup. Observe it without any emotional response or story.",
     "instructions": ["Visualize the white cup.", "Observe it neutrally.",
                      "If emotional associations arise, return to pure observation.", "Rate the neutrality achieved."],
     "duration_seconds": 60, "dimension_weights": {"emotion": 0.6, "vividness": 0.4}},
    # ─── SCENE CONSTRUCTION ───
    {"task_id": "simple_room_construction", "title": "Simple Room Construction",
     "category": "scene_construction", "difficulty": 2,
     "target_dimensions": ["spatial_control", "vividness", "detail"],
     "prompt": "Construct a simple room from scratch: four walls, a floor, a ceiling, and one piece of furniture.",
     "instructions": ["Build the four walls.", "Add floor and ceiling.",
                      "Add one chair.", "Hold the full scene.", "Rate construction quality."],
     "duration_seconds": 90, "dimension_weights": {"spatial_control": 0.4, "vividness": 0.3, "detail": 0.3}},
    {"task_id": "beach_scene_construction", "title": "Beach Scene Construction",
     "category": "scene_construction", "difficulty": 3,
     "target_dimensions": ["spatial_control", "vividness", "detail", "color_control"],
     "prompt": "Construct a beach scene: sand, ocean, sky, and one element of your choice.",
     "instructions": ["Build the sand and ocean horizon.", "Add the sky with color.",
                      "Add your chosen element (boat, shell, umbrella).", "Hold the full scene.", "Rate construction."],
     "duration_seconds": 120, "dimension_weights": {"spatial_control": 0.3, "vividness": 0.3, "detail": 0.2, "color_control": 0.2}},
    {"task_id": "symbolic_doorway_scene", "title": "Symbolic Doorway Scene",
     "category": "scene_construction", "difficulty": 4,
     "target_dimensions": ["spatial_control", "emotion", "detail"],
     "prompt": "Construct a scene with a doorway. Add one symbolic element. Let the scene feel personally meaningful.",
     "instructions": ["Build a doorway in a wall.", "Add lighting and texture.",
                      "Add one symbolic personal element.", "Hold the scene and emotional tone.",
                      "Rate construction and emotional quality.",
                      "Safety: if the scene becomes emotionally difficult, stop."],
     "duration_seconds": 120, "dimension_weights": {"spatial_control": 0.4, "emotion": 0.3, "detail": 0.3},
     "safety_note": "If the scene becomes emotionally difficult or uncomfortable, stop immediately."},
    # ─── MULTISENSORY IMAGERY ───
    {"task_id": "visual_plus_sound_scene", "title": "Visual + Sound Scene",
     "category": "multisensory_imagery", "difficulty": 3,
     "target_dimensions": ["multisensory", "vividness"],
     "prompt": "Visualize ocean waves AND imagine the sound of waves breaking on the shore simultaneously.",
     "instructions": ["Build the ocean wave visual.", "Add the wave sound.",
                      "Hold both visual and audio simultaneously.", "Rate multisensory integration."],
     "duration_seconds": 90, "dimension_weights": {"multisensory": 0.7, "vividness": 0.3}},
    {"task_id": "visual_plus_touch_object", "title": "Visual + Touch Object",
     "category": "multisensory_imagery", "difficulty": 3,
     "target_dimensions": ["multisensory", "vividness"],
     "prompt": "Visualize holding a smooth stone. Imagine its weight, temperature, and texture in your hand.",
     "instructions": ["Build the stone visual.", "Add the sensation of weight.",
                      "Add the texture feeling in your palm.", "Add temperature.", "Rate multisensory quality."],
     "duration_seconds": 90, "dimension_weights": {"multisensory": 0.8, "vividness": 0.2}},
    {"task_id": "visual_plus_smell_food", "title": "Visual + Smell Food",
     "category": "multisensory_imagery", "difficulty": 4,
     "target_dimensions": ["multisensory", "vividness", "detail"],
     "prompt": "Visualize a fresh orange being peeled. Imagine the citrus scent released as the peel separates.",
     "instructions": ["Build the orange visual.", "Add the peeling action.",
                      "Add the citrus scent sensation.", "Hold visual, action, and scent together.",
                      "Rate multisensory integration."],
     "duration_seconds": 90, "dimension_weights": {"multisensory": 0.6, "vividness": 0.2, "detail": 0.2}},
    # ─── META-CONTROL ───
    {"task_id": "hold_image_30_seconds", "title": "Hold Image 30 Seconds",
     "category": "meta_control", "difficulty": 1,
     "target_dimensions": ["meta_control", "vividness", "stability"],
     "prompt": "Visualize a simple red circle. Hold it steadily in your mind for the full 30 seconds without fading.",
     "instructions": ["Build the red circle.", "Hold it without fading, shifting, or changing.",
                      "If it fades, rebuild and continue.", "Rate how long and steadily you held it."],
     "duration_seconds": 30, "dimension_weights": {"meta_control": 0.5, "vividness": 0.3, "stability": 0.2}},
    {"task_id": "intentionally_blur_then_refocus", "title": "Blur Then Refocus",
     "category": "meta_control", "difficulty": 3,
     "target_dimensions": ["meta_control", "vividness", "detail"],
     "prompt": "Visualize a clear image, intentionally blur it, then sharpen and restore full clarity.",
     "instructions": ["Build a clear image of a chair.", "Intentionally blur it.",
                      "Hold the blurred state for a moment.", "Sharpen back to full clarity.", "Rate meta-control."],
     "duration_seconds": 90, "dimension_weights": {"meta_control": 0.5, "vividness": 0.3, "detail": 0.2}},
    {"task_id": "switch_between_two_images", "title": "Switch Between Two Images",
     "category": "meta_control", "difficulty": 4,
     "target_dimensions": ["meta_control", "vividness", "spatial_control"],
     "prompt": "Visualize an apple, then switch to a banana, then back to the apple, smoothly and deliberately.",
     "instructions": ["Build the apple image.", "Switch to banana image.",
                      "Hold banana.", "Switch back to apple.", "Repeat one more cycle.", "Rate switching control."],
     "duration_seconds": 120, "dimension_weights": {"meta_control": 0.5, "vividness": 0.25, "spatial_control": 0.25}},
]

RATING_SCHEMA = {
    "vividness": {"label": "Vividness", "min": 1, "max": 10,
                  "description": "How clear and photograph-like was the mental image?"},
    "stability": {"label": "Stability", "min": 1, "max": 10,
                  "description": "How stable was the image — did it stay put or drift?"},
    "color_control": {"label": "Color Control", "min": 1, "max": 10,
                      "description": "How well could you control or perceive color?"},
    "spatial_control": {"label": "Spatial Control", "min": 1, "max": 10,
                        "description": "How well could you control position, depth, and perspective?"},
    "detail": {"label": "Detail", "min": 1, "max": 10,
               "description": "How much fine detail were you able to generate?"},
    "motion": {"label": "Motion", "min": 1, "max": 10,
               "description": "How smooth and controlled was the motion you imagined?"},
    "emotion": {"label": "Emotion", "min": 1, "max": 10,
                "description": "How much emotional tone were you able to perceive or control?"},
    "multisensory": {"label": "Multisensory", "min": 1, "max": 10,
                     "description": "How well could you combine visual with other senses?"},
    "meta_control": {"label": "Meta-Control", "min": 1, "max": 10,
                     "description": "How well could you intentionally manipulate your mental image?"},
    "effort": {"label": "Effort", "min": 1, "max": 10,
               "description": "How much mental effort did this task require?"},
    "fatigue": {"label": "Fatigue", "min": 1, "max": 10,
                "description": "How fatigued or mentally tired do you feel after this task?"},
    "confidence": {"label": "Confidence", "min": 1, "max": 10,
                   "description": "How confident are you in your self-ratings?"},
}


def get_imagery_task_registry():
    tasks_with_safety = []
    for t in TASKS:
        tasks_with_safety.append({**t, **SAFETY})
    return {"categories": CATEGORIES, "n_tasks": len(TASKS), "tasks": tasks_with_safety}


def get_imagery_task(task_id):
    for t in TASKS:
        if t["task_id"] == task_id:
            return {**t, **SAFETY}
    return {"error": "task_not_found", "task_id": task_id, "message": f"No task with ID '{task_id}'.", **SAFETY}


def list_imagery_tasks(category=None):
    if category and category not in CATEGORIES:
        return {"tasks": [], "n_tasks": 0, "warning": f"Unknown category '{category}'. Valid: {CATEGORIES}", **SAFETY}
    filtered = [t for t in TASKS if not category or t["category"] == category]
    return {"tasks": [{**t, **SAFETY} for t in filtered], "n_tasks": len(filtered), **SAFETY}
