from app.core.constants import DISCLAIMER
from app.schemas.reports import SessionSummary

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>IMAGINA Session Report — {session_id}</title>
<style>
  body {{
    font-family: system-ui, sans-serif; background: #0a0a0f;
    color: #e4e4ef; max-width: 700px; margin: 40px auto; padding: 20px;
  }}
  h1 {{ color: #818cf8; }}
  .card {{
    background: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.08);
    border-radius: 12px; padding: 20px; margin: 16px 0;
  }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
  .metric {{ text-align: center; }}
  .metric .value {{
    font-size: 24px; font-weight: bold;
    font-family: monospace; color: #818cf8;
  }}
  .metric .label {{ font-size: 12px; color: #888; }}
  .disclaimer {{
    font-size: 11px; color: #666;
    border-left: 3px solid #f59e0b; padding: 8px 12px; margin: 20px 0;
  }}
  .recommendation {{ font-style: italic; color: #aaa; }}
</style>
</head>
<body>
<h1>IMAGINA V1 Session Report</h1>
<div class="disclaimer">{disclaimer}</div>
<div class="card">
  <h2>Summary</h2>
  <div class="grid">
    <div class="metric"><div class="value">{avg_iqi}</div><div class="label">Average IQI</div></div>
    <div class="metric"><div class="value">{avg_pid}</div><div class="label">Average PID</div></div>
    <div class="metric"><div class="value">{best_iqi}</div><div class="label">Best IQI</div></div>
    <div class="metric"><div class="value">{best_pid}</div><div class="label">Best PID</div></div>
    <div class="metric"><div class="value">{duration}</div><div class="label">Duration</div></div>
    <div class="metric"><div class="value">{max_level}</div><div class="label">Max Level</div></div>
    <div class="metric"><div class="value">{streak}</div><div class="label">Best Streak</div></div>
    <div class="metric"><div class="value">{fatigue}</div><div class="label">Fatigue Peak</div></div>
    <div class="metric"><div class="value">{safety}</div><div class="label">Safety Events</div></div>
  </div>
</div>
<div class="card">
  <h2>Recommendation</h2>
  <p class="recommendation">{recommendation}</p>
</div>
<p style="font-size:10px;color:#444;text-align:center;margin-top:40px;">
  Generated by IMAGINA V1 — experimental research prototype
</p>
</body>
</html>"""


def generate_html_report(summary: SessionSummary) -> str:
    m, s = divmod(int(summary.duration_seconds), 60)
    return _TEMPLATE.format(
        session_id=summary.session_id,
        disclaimer=DISCLAIMER,
        avg_iqi=f"{summary.average_iqi:.0%}",
        avg_pid=f"{summary.average_pid:.2f}",
        best_iqi=f"{summary.best_iqi:.0%}",
        best_pid=f"{summary.best_pid:.2f}",
        duration=f"{m}:{s:02d}",
        max_level=summary.max_level_reached,
        streak=f"{summary.best_stability_streak_seconds:.0f}s",
        fatigue=f"{summary.fatigue_peak:.0%}",
        safety=summary.safety_events_count,
        recommendation=summary.recommendation,
    )
